import Drawer from "@/components/Drawer/Drawer";
import { Providers } from "@/components/Providers";
import TheFooter from "@/components/TheFooter/TheFooter";
import TheHeader from "@/components/TheHeader/TheHeader";
import { Metadata } from "next";
import '../styles/index.scss';


export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body>
        <Providers>
          <TheHeader />
          <Drawer />
          <main className="container">{children}</main>
          <TheFooter />
        </Providers>
      </body>
    </html>
  );
}
